version: '2.1'

services:
  rpa-dg-template-management-api:
    build:
      context: .
    image: hmcts/rpa-dg-template-management-api:latest
    environment:
      - SERVER_PORT=8080
      - IDAM_USER_BASE_URI=http://betadevaccidamapplb.reform.hmcts.net
      - IDAM_S2S_BASE_URI=http://service-auth-provider-api:8080
      - APPINSIGHTS_INSTRUMENTATIONKEY=test_app
    # these environment variables are used by java-logging library
      - JSON_CONSOLE_PRETTY_PRINT=false
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=rpa-dg-template-management-api
      - REFORM_TEAM=dg-template-management-api
      - REFORM_ENVIRONMENT=docker
    ports:
    - $SERVER_PORT:8080
