tmpl-mgmt-api:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  applicationPort: 8080
  readinessDelay: 20
  readinessTimeout: 20
  readinessFailureThreshold: 7
  readinessPeriod: 15
  livenessDelay: 20
  livenessTimeout: 20
  livenessPeriod: 15
  livenessFailureThreshold: 7
  keyVaults:
    rpa:
      resourceGroup: rpa
      secrets:
        - AppInsightsInstrumentationKey
    s2s:
      resourceGroup: rpe-service-auth-provider
      secrets:
        - microservicekey-dg-template-management
  environment:
    REFORM_SERVICE_TYPE: java
    REFORM_SERVICE_NAME: rpa-dg-template-management-api
    REFORM_TEAM: dg-template-management-api
    REFORM_ENVIRONMENT: preview
    IDAM_API_BASE_URI: https://preprod-idamapi.reform.hmcts.net:3511
    S2S_BASE_URI: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal